### ISSUE TITLE
Your game has been copied

### ISSUE THREAD

**Issue by vanproskur** [Kerbalximus/custom-dino#2]
KerbalX ты даун чо ты плагиатишь игры

**Comment by Kerbalximus** [comment]
Это игра моя. Но каждый может использовать её исходный код!

**Comment by vanproskur** [comment]
ок , я заливаю ее к себе в гитхаб xD

**Comment by vanproskur** [comment]
и кста гитхаб обратите внимание, он меня насильно заставил удалить репозиторий у меня и украл у меня игру

**Comment by Kerbalximus** [comment]
Возможно я скопировал спрайты. Но исходный код полностью мой. Вы можете использовать файлы игры Custom Dino!!! только с указанием на официальный источник которым является - https://github.com/Kerbalximus/custom-dino/
