### ISSUE TITLE
Твой говнокод тошно смотреть 

### ISSUE THREAD

**Issue by vanproskur** [Kerbalximus/custom-dino#3]
Удали МОЙ ДИНО С ТВОЕГО ГИТХАБА

**Comment by Kerbalximus** [comment]
Возможно я скопировал спрайты. Но исходный код полностью мой. Вы можете использовать файлы игры Custom Dino !!! только с указанием на официальный источник является https://github.com/Kerbalximus/custom-dino/
Если остались вопросы по авторским правам то пишите на: kerbalx.kerbalx@gmail.com
